// services/phrases.js
// Sayt boyu şablonlarda qalan Azərbaycan dilindəki mətnlərin tərcümə lüğəti.
// Açar = mənbə (AZ) mətn, dəyər = { en, tr, ru, ka }.
// i18n.middleware render nəticəsini (HTML) bu lüğətlə tərcümə edir —
// beləliklə hər EJS faylını tək-tək dəyişmədən bütün sayt tərcümə olunur.

module.exports = {
  // ── Ümumi / naviqasiya ──
  'Ana səhifə':        { en: 'Home', tr: 'Ana sayfa', ru: 'Главная', ka: 'მთავარი' },
  'Qaliblər':          { en: 'Winners', tr: 'Kazananlar', ru: 'Победители', ka: 'გამარჯვებულები' },
  'Profil':            { en: 'Profile', tr: 'Profil', ru: 'Профиль', ka: 'პროფილი' },
  'Profilə qayıt':     { en: 'Back to profile', tr: 'Profile dön', ru: 'Назад в профиль', ka: 'პროფილზე დაბრუნება' },
  'Parametrlər':       { en: 'Settings', tr: 'Ayarlar', ru: 'Настройки', ka: 'პარამეტრები' },
  'Çıxış':             { en: 'Log out', tr: 'Çıkış', ru: 'Выход', ka: 'გასვლა' },
  'Balansınız':        { en: 'Your balance', tr: 'Bakiyeniz', ru: 'Ваш баланс', ka: 'თქვენი ბალანსი' },
  'Balansınıza':       { en: 'to your balance', tr: 'bakiyenize', ru: 'на ваш баланс', ka: 'თქვენს ბალანსზე' },
  'Yüklə':             { en: 'Deposit', tr: 'Yatır', ru: 'Пополнить', ka: 'შევსება' },
  'Çıxar':             { en: 'Withdraw', tr: 'Çek', ru: 'Вывести', ka: 'გატანა' },
  'Kopyala':           { en: 'Copy', tr: 'Kopyala', ru: 'Копировать', ka: 'კოპირება' },
  'Kopyalandı':        { en: 'Copied', tr: 'Kopyalandı', ru: 'Скопировано', ka: 'დაკოპირდა' },
  '✓ Kopyalandı':      { en: '✓ Copied', tr: '✓ Kopyalandı', ru: '✓ Скопировано', ka: '✓ დაკოპირდა' },
  'Bağla':             { en: 'Close', tr: 'Kapat', ru: 'Закрыть', ka: 'დახურვა' },
  'Əlavə':             { en: 'Add', tr: 'Ekle', ru: 'Добавить', ka: 'დამატება' },
  'Artır':             { en: 'Top up', tr: 'Yükle', ru: 'Пополнить', ka: 'შევსება' },
  'Ümumi':             { en: 'Total', tr: 'Toplam', ru: 'Всего', ka: 'სულ' },
  'və ya':             { en: 'or', tr: 'veya', ru: 'или', ka: 'ან' },
  'Şəbəkə xətası':     { en: 'Network error', tr: 'Ağ hatası', ru: 'Ошибка сети', ka: 'ქსელის შეცდომა' },
  'Xəta baş verdi':    { en: 'Something went wrong', tr: 'Bir hata oluştu', ru: 'Произошла ошибка', ka: 'დაფიქსირდა შეცდომა' },
  'Yenilənmədi':       { en: 'Not updated', tr: 'Güncellenmedi', ru: 'Не обновлено', ka: 'არ განახლდა' },
  'Alınmadı':          { en: 'Failed', tr: 'Başarısız', ru: 'Не удалось', ka: 'ვერ მოხერხდა' },
  'Təsdiqlənib':       { en: 'Verified', tr: 'Onaylandı', ru: 'Подтверждено', ka: 'დადასტურებულია' },
  'təsdiqli':          { en: 'verified', tr: 'onaylı', ru: 'подтверждён', ka: 'დადასტურებული' },
  'Aktivləşdir':       { en: 'Activate', tr: 'Etkinleştir', ru: 'Активировать', ka: 'გააქტიურება' },
  'Sonlandır':         { en: 'End', tr: 'Sonlandır', ru: 'Завершить', ka: 'დასრულება' },
  'Doğrula':           { en: 'Verify', tr: 'Doğrula', ru: 'Подтвердить', ka: 'დადასტურება' },
  '7/24 dəstək':       { en: '24/7 support', tr: '7/24 destek', ru: 'Поддержка 24/7', ka: '24/7 მხარდაჭერა' },
  'bizə ulaşın':       { en: 'contact us', tr: 'bize ulaşın', ru: 'свяжитесь с нами', ka: 'დაგვიკავშირდით' },
  'One Loto — Bütün hüquqlar qorunur.': { en: 'One Loto — All rights reserved.', tr: 'One Loto — Tüm hakları saklıdır.', ru: 'One Loto — Все права защищены.', ka: 'One Loto — ყველა უფლება დაცულია.' },
  '© 2026. Bütün hüquqlar qorunur.': { en: '© 2026. All rights reserved.', tr: '© 2026. Tüm hakları saklıdır.', ru: '© 2026. Все права защищены.', ka: '© 2026. ყველა უფლება დაცულია.' },
  'Lisenziyalı əyləncə platforması.': { en: 'Licensed entertainment platform.', tr: 'Lisanslı eğlence platformu.', ru: 'Лицензированная развлекательная платформа.', ka: 'ლიცენზირებული გასართობი პლატფორმა.' },
  'Bütün nəticələr təsadüfi qaydada müəyyənləşir, hesablar şifrələnərək qorunur.': { en: 'All results are determined randomly and accounts are protected with encryption.', tr: 'Tüm sonuçlar rastgele belirlenir, hesaplar şifrelenerek korunur.', ru: 'Все результаты определяются случайным образом, аккаунты защищены шифрованием.', ka: 'ყველა შედეგი შემთხვევითად განისაზღვრება, ანგარიშები დაშიფრულია.' },

  // ── Profil / hesab ──
  'Oynanılan oyunlar': { en: 'Games played', tr: 'Oynanan oyunlar', ru: 'Сыграно игр', ka: 'ნათამაშები თამაშები' },
  'Qazanılan oyunlar': { en: 'Games won', tr: 'Kazanılan oyunlar', ru: 'Побед', ka: 'მოგებული თამაშები' },
  'Ümumi qazanc':      { en: 'Total winnings', tr: 'Toplam kazanç', ru: 'Общий выигрыш', ka: 'ჯამური მოგება' },
  'Oynanılan':         { en: 'Played', tr: 'Oynanan', ru: 'Сыграно', ka: 'ნათამაშები' },
  'Qazanılan':         { en: 'Won', tr: 'Kazanılan', ru: 'Выиграно', ka: 'მოგებული' },
  'Referral kodu':     { en: 'Referral code', tr: 'Referans kodu', ru: 'Реферальный код', ka: 'რეფერალური კოდი' },
  'Referral kodunuz':  { en: 'Your referral code', tr: 'Referans kodunuz', ru: 'Ваш реферальный код', ka: 'თქვენი რეფერალური კოდი' },
  'Referral linkiniz': { en: 'Your referral link', tr: 'Referans linkiniz', ru: 'Ваша реферальная ссылка', ka: 'თქვენი რეფერალური ბმული' },
  'Dostları dəvət et': { en: 'Invite friends', tr: 'Arkadaşlarını davet et', ru: 'Пригласить друзей', ka: 'მეგობრების მოწვევა' },
  'Dostları dəvət et, qazanc əldə et!': { en: 'Invite friends and earn rewards!', tr: 'Arkadaşlarını davet et, kazanç elde et!', ru: 'Приглашайте друзей и зарабатывайте!', ka: 'მოიწვიე მეგობრები და გამოიმუშავე!' },
  'Hər dəvət etdiyiniz dostun qeydiyyatdan keçməsi ilə bonus balans qazanırsınız.': { en: 'You earn a bonus balance for every friend who signs up.', tr: 'Kayıt olan her arkadaşın için bonus bakiye kazanırsın.', ru: 'За каждого зарегистрировавшегося друга вы получаете бонус.', ka: 'ყოველი დარეგისტრირებული მეგობრისთვის იღებთ ბონუსს.' },
  'Hər qeydiyyatdan 0.50 ₼ bonus': { en: '0.50 bonus for every sign-up', tr: 'Her kayıttan 0.50 bonus', ru: 'Бонус 0.50 за регистрацию', ka: '0.50 ბონუსი ყოველ რეგისტრაციაზე' },
  'Dəvət edilənlər':   { en: 'Invited', tr: 'Davet edilenler', ru: 'Приглашено', ka: 'მოწვეულები' },
  'Qazanılan bonus':   { en: 'Bonus earned', tr: 'Kazanılan bonus', ru: 'Заработанный бонус', ka: 'მიღებული ბონუსი' },
  'Necə işləyir?':     { en: 'How does it work?', tr: 'Nasıl çalışır?', ru: 'Как это работает?', ka: 'როგორ მუშაობს?' },
  'Linki paylaşın':    { en: 'Share the link', tr: 'Linki paylaş', ru: 'Поделитесь ссылкой', ka: 'გააზიარეთ ბმული' },
  '— dostlarınıza referral linkinizi göndərin': { en: '— send your referral link to friends', tr: '— referans linkini arkadaşlarına gönder', ru: '— отправьте реферальную ссылку друзьям', ka: '— გაუგზავნეთ ბმული მეგობრებს' },
  'Dost qeydiyyatdan keçir': { en: 'Your friend signs up', tr: 'Arkadaşın kayıt olur', ru: 'Друг регистрируется', ka: 'მეგობარი რეგისტრირდება' },
  '— dostunuz linki açıb qeydiyyatdan keçir': { en: '— your friend opens the link and signs up', tr: '— arkadaşın linki açıp kayıt olur', ru: '— друг открывает ссылку и регистрируется', ka: '— მეგობარი ხსნის ბმულს და რეგისტრირდება' },
  'Bonus alırsınız':   { en: 'You get a bonus', tr: 'Bonus alırsın', ru: 'Вы получаете бонус', ka: 'იღებთ ბონუსს' },
  '— 0.50 ₼ bonus balansınıza avtomatik əlavə edilir': { en: '— a 0.50 bonus is added to your balance automatically', tr: '— 0.50 bonus otomatik bakiyene eklenir', ru: '— бонус 0.50 автоматически зачисляется на баланс', ka: '— 0.50 ბონუსი ავტომატურად ემატება ბალანსს' },
  'Dost dəvət linki':  { en: 'Friend invite link', tr: 'Arkadaş davet linki', ru: 'Ссылка-приглашение', ka: 'მოწვევის ბმული' },
  'Bu linklə qeydiyyatdan keçən dostunuz üçün balansınıza': { en: 'For each friend who signs up with this link, your balance gets', tr: 'Bu linkle kayıt olan her arkadaşın için bakiyene', ru: 'За друга, зарегистрировавшегося по ссылке, на баланс', ka: 'ამ ბმულით დარეგისტრირებული მეგობრისთვის თქვენს ბალანსს' },
  'bonus yazılır.':    { en: 'bonus credited.', tr: 'bonus eklenir.', ru: 'начисляется бонус.', ka: 'ერიცხება ბონუსი.' },
  'Bonus hər cihaz üçün yalnız': { en: 'The bonus is granted only once per device', tr: 'Bonus her cihaz için yalnızca', ru: 'Бонус выдаётся только один раз на устройство', ka: 'ბონუსი მხოლოდ ერთხელ ერთ მოწყობილობაზე' },
  '1 dəfə':            { en: 'once', tr: '1 kez', ru: '1 раз', ka: '1-ჯერ' },
  'verilir — eyni cihazda yenidən hesab açıldıqda təkrarlanmır.': { en: '— it is not repeated when a new account is opened on the same device.', tr: '— aynı cihazda yeni hesap açıldığında tekrarlanmaz.', ru: '— при создании нового аккаунта на том же устройстве не повторяется.', ka: '— იმავე მოწყობილობაზე ახალი ანგარიშისთვის აღარ მეორდება.' },
  'İstifadəçi adı':    { en: 'Username', tr: 'Kullanıcı adı', ru: 'Имя пользователя', ka: 'მომხმარებლის სახელი' },
  'İstifadəçi ID':     { en: 'User ID', tr: 'Kullanıcı ID', ru: 'ID пользователя', ka: 'მომხმარებლის ID' },
  'İstifadəçi':        { en: 'User', tr: 'Kullanıcı', ru: 'Пользователь', ka: 'მომხმარებელი' },
  'E-poçt':            { en: 'E-mail', tr: 'E-posta', ru: 'E-mail', ka: 'ელფოსტა' },
  'Telefon nömrəsi':   { en: 'Phone number', tr: 'Telefon numarası', ru: 'Номер телефона', ka: 'ტელეფონის ნომერი' },
  'Ad və soyadınız':   { en: 'Your full name', tr: 'Ad ve soyadınız', ru: 'Ваше имя и фамилия', ka: 'თქვენი სახელი და გვარი' },
  'Şəxsiyyət məlumatları': { en: 'Identity details', tr: 'Kimlik bilgileri', ru: 'Данные документа', ka: 'პირადობის მონაცემები' },
  'Passport nömrəsi':  { en: 'Passport number', tr: 'Pasaport numarası', ru: 'Номер паспорта', ka: 'პასპორტის ნომერი' },
  'Passport şəkili':   { en: 'Passport photo', tr: 'Pasaport fotoğrafı', ru: 'Фото паспорта', ka: 'პასპორტის ფოტო' },
  'Passport şəkilini əlavə et': { en: 'Attach a passport photo', tr: 'Pasaport fotoğrafı ekle', ru: 'Добавьте фото паспорта', ka: 'დაამატეთ პასპორტის ფოტო' },
  'Üz şəkili':         { en: 'Selfie', tr: 'Yüz fotoğrafı', ru: 'Селфи', ka: 'სელფი' },
  'Üz şəkilinizi əlavə et': { en: 'Attach your selfie', tr: 'Yüz fotoğrafını ekle', ru: 'Добавьте селфи', ka: 'დაამატეთ სელფი' },
  'Yaşınız':           { en: 'Your age', tr: 'Yaşınız', ru: 'Ваш возраст', ka: 'თქვენი ასაკი' },
  'Yaş təsdiqləndi (': { en: 'Age verified (', tr: 'Yaş doğrulandı (', ru: 'Возраст подтверждён (', ka: 'ასაკი დადასტურდა (' },
  'Qeydiyyat yalnız 18 yaşdan yuxarı şəxslər üçündür.': { en: 'Registration is only for people aged 18 and over.', tr: 'Kayıt yalnızca 18 yaş üstü kişiler içindir.', ru: 'Регистрация только для лиц старше 18 лет.', ka: 'რეგისტრაცია მხოლოდ 18 წლის ზემოთ პირებისთვის.' },
  '— 18 yaşdan kiçik şəxslər qeydiyyatdan keçə bilməz.': { en: '— people under 18 cannot register.', tr: '— 18 yaşından küçükler kayıt olamaz.', ru: '— лица младше 18 лет не могут зарегистрироваться.', ka: '— 18 წლამდე პირები ვერ დარეგისტრირდებიან.' },
  'istifadəçilər üçün nəzərdə tutulub.': { en: 'is intended for users.', tr: 'kullanıcılar içindir.', ru: 'предназначено для пользователей.', ka: 'განკუთვნილია მომხმარებლებისთვის.' },
  'Şəkil 6 MB-dan böyük olmamalıdır': { en: 'The image must not exceed 6 MB', tr: 'Görsel 6 MB’dan büyük olmamalı', ru: 'Изображение не должно превышать 6 МБ', ka: 'სურათი არ უნდა აღემატებოდეს 6 MB-ს' },
  'Maksimum istifadəçi': { en: 'Maximum users', tr: 'Maksimum kullanıcı', ru: 'Максимум пользователей', ka: 'მაქსიმალური მომხმარებელი' },
  'Digər cihazlardan çıxış': { en: 'Log out other devices', tr: 'Diğer cihazlardan çıkış', ru: 'Выйти на других устройствах', ka: 'სხვა მოწყობილობებიდან გასვლა' },
  'Aktiv oturum izlərilmir.': { en: 'No active sessions are being tracked.', tr: 'Aktif oturum izlenmiyor.', ru: 'Активные сессии не отслеживаются.', ka: 'აქტიური სესიები არ ფიქსირდება.' },
  'Bütün əlaqə məlumatları': { en: 'All contact details', tr: 'Tüm iletişim bilgileri', ru: 'Все контактные данные', ka: 'ყველა საკონტაქტო მონაცემი' },
  'Onaylanmış dəyişiklik üçün': { en: 'For an approved change', tr: 'Onaylı değişiklik için', ru: 'Для подтверждённого изменения', ka: 'დადასტურებული ცვლილებისთვის' },
  'Başqa hesabla davam et': { en: 'Continue with another account', tr: 'Başka hesapla devam et', ru: 'Продолжить с другим аккаунтом', ka: 'სხვა ანგარიშით გაგრძელება' },

  // ── Şifrə ──
  'Şifrəni dəyiş':     { en: 'Change password', tr: 'Şifre değiştir', ru: 'Сменить пароль', ka: 'პაროლის შეცვლა' },
  'Şifrəni Dəyiş':     { en: 'Change Password', tr: 'Şifre Değiştir', ru: 'Смена пароля', ka: 'პაროლის შეცვლა' },
  'Köhnə şifrə':       { en: 'Current password', tr: 'Eski şifre', ru: 'Старый пароль', ka: 'ძველი პაროლი' },
  'Mövcud şifrəniz':   { en: 'Your current password', tr: 'Mevcut şifreniz', ru: 'Ваш текущий пароль', ka: 'თქვენი მიმდინარე პაროლი' },
  'Yeni şifrəniz':     { en: 'Your new password', tr: 'Yeni şifreniz', ru: 'Ваш новый пароль', ka: 'თქვენი ახალი პაროლი' },
  'Yeni şifrə (min. 6 simvol)': { en: 'New password (min. 6 characters)', tr: 'Yeni şifre (min. 6 karakter)', ru: 'Новый пароль (мин. 6 символов)', ka: 'ახალი პაროლი (მინ. 6 სიმბოლო)' },
  'Yeni şifrə (min 6 simvol)': { en: 'New password (min 6 characters)', tr: 'Yeni şifre (min 6 karakter)', ru: 'Новый пароль (мин 6 символов)', ka: 'ახალი პაროლი (მინ 6 სიმბოლო)' },
  'Yeni şifrəni təsdiqlə': { en: 'Confirm new password', tr: 'Yeni şifreyi onayla', ru: 'Подтвердите новый пароль', ka: 'დაადასტურეთ ახალი პაროლი' },
  'Yeni şifrəni təkrarlayın': { en: 'Repeat the new password', tr: 'Yeni şifreyi tekrarlayın', ru: 'Повторите новый пароль', ka: 'გაიმეორეთ ახალი პაროლი' },
  'Köhnə şifrə yanlışdır': { en: 'The current password is incorrect', tr: 'Eski şifre yanlış', ru: 'Старый пароль неверен', ka: 'ძველი პაროლი არასწორია' },
  'Yeni şifrələr uyğun gəlmir': { en: 'The new passwords do not match', tr: 'Yeni şifreler eşleşmiyor', ru: 'Новые пароли не совпадают', ka: 'ახალი პაროლები არ ემთხვევა' },
  'Şifrə ən az 6 simvol olmalıdır': { en: 'The password must be at least 6 characters', tr: 'Şifre en az 6 karakter olmalı', ru: 'Пароль должен быть не менее 6 символов', ka: 'პაროლი უნდა იყოს მინიმუმ 6 სიმბოლო' },
  'Şifrə uğurla dəyişdirildi': { en: 'Password changed successfully', tr: 'Şifre başarıyla değiştirildi', ru: 'Пароль успешно изменён', ka: 'პაროლი წარმატებით შეიცვალა' },
  'ⓘ Şifrəniz heç vaxt e-poçt və ya Telegram vasitəsilə soruşulmur. Şübhəli sorğu aldığınızda dərhal': { en: 'ⓘ We never ask for your password by e-mail or Telegram. If you receive a suspicious request, write immediately to', tr: 'ⓘ Şifreniz asla e-posta veya Telegram ile sorulmaz. Şüpheli bir istek alırsanız hemen', ru: 'ⓘ Мы никогда не спрашиваем пароль по e-mail или в Telegram. При подозрительном запросе сразу напишите на', ka: 'ⓘ პაროლს არასდროს გეკითხებით ელფოსტით ან Telegram-ით. საეჭვო მოთხოვნისას მიწერეთ' },
  'ünvanına yazın.':   { en: 'address.', tr: 'adresine yazın.', ru: 'адрес.', ka: 'მისამართზე.' },
  'Məlumatlar yeniləndi': { en: 'Details updated', tr: 'Bilgiler güncellendi', ru: 'Данные обновлены', ka: 'მონაცემები განახლდა' },
  'Bu istifadəçi adı mövcuddur': { en: 'This username already exists', tr: 'Bu kullanıcı adı mevcut', ru: 'Такое имя пользователя уже есть', ka: 'ეს მომხმარებლის სახელი უკვე არსებობს' },

  // ── E-poçt doğrulaması ──
  'E-poçtunu doğrula': { en: 'Verify your e-mail', tr: 'E-postanı doğrula', ru: 'Подтвердите e-mail', ka: 'დაადასტურეთ ელფოსტა' },
  'Doğrulama gerekli': { en: 'Verification required', tr: 'Doğrulama gerekli', ru: 'Требуется подтверждение', ka: 'საჭიროა დადასტურება' },
  '6 rəqəmli kod':     { en: '6-digit code', tr: '6 haneli kod', ru: '6-значный код', ka: '6-ნიშნა კოდი' },
  'Yeni kod göndər':   { en: 'Send a new code', tr: 'Yeni kod gönder', ru: 'Отправить новый код', ka: 'ახალი კოდის გაგზავნა' },
  'adresinə göndərildi.': { en: 'address.', tr: 'adresine gönderildi.', ru: 'адрес отправлено.', ka: 'მისამართზე გაიგზავნა.' },
  'Kod gəlmədi? Spam qovluğunu yoxlayın.': { en: 'No code? Check your spam folder.', tr: 'Kod gelmedi mi? Spam klasörünü kontrol edin.', ru: 'Код не пришёл? Проверьте папку «Спам».', ka: 'კოდი არ მოვიდა? შეამოწმეთ სპამი.' },
  'Kodun vaxtı bitdi — bloke olundu': { en: 'The code expired — it is now blocked', tr: 'Kodun süresi doldu — bloke edildi', ru: 'Срок кода истёк — заблокирован', ka: 'კოდის ვადა ამოიწურა — დაიბლოკა' },
  'etibarlıdır — vaxt bitdikdə kod bloke olunur.': { en: 'is valid — the code is blocked once the time runs out.', tr: 'geçerlidir — süre dolduğunda kod bloke olur.', ru: 'действителен — по истечении времени код блокируется.', ka: 'მოქმედებს — დროის ამოწურვისას კოდი იბლოკება.' },
  '3 dəqiqə':          { en: '3 minutes', tr: '3 dakika', ru: '3 минуты', ka: '3 წუთი' },

  // ── Oyun / otaqlar ──
  'Oyun otaqları':     { en: 'Game rooms', tr: 'Oyun odaları', ru: 'Игровые комнаты', ka: 'სათამაშო ოთახები' },
  'Oyun tarixçəsi':    { en: 'Game history', tr: 'Oyun geçmişi', ru: 'История игр', ka: 'თამაშების ისტორია' },
  'Oyun Tarixçəsi':    { en: 'Game History', tr: 'Oyun Geçmişi', ru: 'История игр', ka: 'თამაშების ისტორია' },
  'Son 50 oyununuz':   { en: 'Your last 50 games', tr: 'Son 50 oyunun', ru: 'Ваши последние 50 игр', ka: 'თქვენი ბოლო 50 თამაში' },
  'Hələ heç bir oyun yoxdur': { en: 'No games yet', tr: 'Henüz oyun yok', ru: 'Игр пока нет', ka: 'თამაშები ჯერ არ არის' },
  'İlk oyununuzu oynamağa başlayın!': { en: 'Start playing your first game!', tr: 'İlk oyununu oynamaya başla!', ru: 'Сыграйте свою первую игру!', ka: 'დაიწყეთ პირველი თამაში!' },
  'Qalib! 🎊':         { en: 'Winner! 🎊', tr: 'Kazandın! 🎊', ru: 'Победа! 🎊', ka: 'გამარჯვება! 🎊' },
  'Udulmadı':          { en: 'No win', tr: 'Kazanılmadı', ru: 'Без выигрыша', ka: 'მოგება არ არის' },
  'Otaq yarat':        { en: 'Create room', tr: 'Oda oluştur', ru: 'Создать комнату', ka: 'ოთახის შექმნა' },
  'Otağı yarat':       { en: 'Create the room', tr: 'Odayı oluştur', ru: 'Создать комнату', ka: 'ოთახის შექმნა' },
  'Şəxsi otaq yarat':  { en: 'Create a private room', tr: 'Özel oda oluştur', ru: 'Создать приватную комнату', ka: 'პირადი ოთახის შექმნა' },
  'Öz otağını yarat, mərci təyin et və dostlarını dəvət et.': { en: 'Create your own room, set the stake and invite your friends.', tr: 'Kendi odanı oluştur, bahsi belirle ve arkadaşlarını davet et.', ru: 'Создайте свою комнату, задайте ставку и пригласите друзей.', ka: 'შექმენით ოთახი, დააყენეთ ფსონი და მოიწვიეთ მეგობრები.' },
  'Otaq adı':          { en: 'Room name', tr: 'Oda adı', ru: 'Название комнаты', ka: 'ოთახის სახელი' },
  'məs: Dostlar otağı': { en: 'e.g. Friends room', tr: 'örn: Arkadaş odası', ru: 'напр.: Комната друзей', ka: 'მაგ.: მეგობრების ოთახი' },
  'Otağa giriş kodu':  { en: 'Room access code', tr: 'Odaya giriş kodu', ru: 'Код доступа к комнате', ka: 'ოთახის კოდი' },
  '– Giriş kodu':      { en: '– Access code', tr: '– Giriş kodu', ru: '– Код доступа', ka: '– წვდომის კოდი' },
  'Bu şəxsi otaqdır. Daxil olmaq üçün giriş kodunu yazın.': { en: 'This is a private room. Enter the access code to join.', tr: 'Bu özel bir oda. Girmek için giriş kodunu yaz.', ru: 'Это приватная комната. Введите код доступа.', ka: 'ეს პირადი ოთახია. შესასვლელად შეიყვანეთ კოდი.' },
  'Giriş kodu yanlışdır': { en: 'The access code is incorrect', tr: 'Giriş kodu yanlış', ru: 'Неверный код доступа', ka: 'წვდომის კოდი არასწორია' },
  '4–12 hərf/rəqəm. Bu kodu dostlarınıza verin.': { en: '4–12 letters/digits. Share this code with your friends.', tr: '4–12 harf/rakam. Bu kodu arkadaşlarına ver.', ru: '4–12 букв/цифр. Передайте код друзьям.', ka: '4–12 ასო/ციფრი. გაუზიარეთ კოდი მეგობრებს.' },
  'Otağa daxil ol':    { en: 'Enter the room', tr: 'Odaya gir', ru: 'Войти в комнату', ka: 'ოთახში შესვლა' },
  'Otağa gir':         { en: 'Join room', tr: 'Odaya gir', ru: 'Войти', ka: 'ოთახში' },
  'Silinmiş otaq':     { en: 'Deleted room', tr: 'Silinmiş oda', ru: 'Удалённая комната', ka: 'წაშლილი ოთახი' },
  'Hazırda aktiv otaq yoxdur': { en: 'There are no active rooms right now', tr: 'Şu anda aktif oda yok', ru: 'Сейчас нет активных комнат', ka: 'ამჟამად აქტიური ოთახი არ არის' },
  'Otaq adını yazın':  { en: 'Enter a room name', tr: 'Oda adını yaz', ru: 'Введите название комнаты', ka: 'შეიყვანეთ ოთახის სახელი' },
  'Şəxsi':             { en: 'Private', tr: 'Özel', ru: 'Приватная', ka: 'პირადი' },
  'Oyunçu gözlənilir': { en: 'Waiting for players', tr: 'Oyuncu bekleniyor', ru: 'Ожидание игроков', ka: 'ველოდებით მოთამაშეებს' },
  'Oyunçular gözlənilir…': { en: 'Waiting for players…', tr: 'Oyuncular bekleniyor…', ru: 'Ожидание игроков…', ka: 'ველოდებით მოთამაშეებს…' },
  'Son qalib gözlənilir': { en: 'Waiting for the latest winner', tr: 'Son kazanan bekleniyor', ru: 'Ожидается последний победитель', ka: 'ველოდებით ბოლო გამარჯვებულს' },
  'onlayn oyunçular':  { en: 'players online', tr: 'çevrimiçi oyuncular', ru: 'игроков онлайн', ka: 'მოთამაშე ონლაინ' },
  'Oyunçular':         { en: 'Players', tr: 'Oyuncular', ru: 'Игроки', ka: 'მოთამაშეები' },
  'Oyunçu':            { en: 'Player', tr: 'Oyuncu', ru: 'Игрок', ka: 'მოთამაშე' },
  'Başladı':           { en: 'Started', tr: 'Başladı', ru: 'Началась', ka: 'დაიწყო' },
  'Başlayır':          { en: 'Starting', tr: 'Başlıyor', ru: 'Начинается', ka: 'იწყება' },
  'Gözləyir':          { en: 'Waiting', tr: 'Bekliyor', ru: 'Ожидание', ka: 'მოლოდინში' },
  'Canlı oyun':        { en: 'Live game', tr: 'Canlı oyun', ru: 'Живая игра', ka: 'ცოცხალი თამაში' },
  'Ümumi mərc':        { en: 'Total stake', tr: 'Toplam bahis', ru: 'Общая ставка', ka: 'ჯამური ფსონი' },
  'Bilet uduşu':       { en: 'Ticket prize', tr: 'Bilet ödülü', ru: 'Выигрыш билета', ka: 'ბილეთის მოგება' },
  'Biletlər':          { en: 'Tickets', tr: 'Biletler', ru: 'Билеты', ka: 'ბილეთები' },
  'Bilet alındı':      { en: 'Ticket purchased', tr: 'Bilet alındı', ru: 'Билет куплен', ka: 'ბილეთი შეძენილია' },
  'bilet alındı':      { en: 'tickets purchased', tr: 'bilet alındı', ru: 'билетов куплено', ka: 'ბილეთი შეძენილია' },
  'Bilet yeniləndi':   { en: 'Ticket refreshed', tr: 'Bilet yenilendi', ru: 'Билет обновлён', ka: 'ბილეთი განახლდა' },
  'Bilet dəyişdirildi': { en: 'Ticket changed', tr: 'Bilet değiştirildi', ru: 'Билет заменён', ka: 'ბილეთი შეიცვალა' },
  'Yeni kart yaradıldı': { en: 'A new card was created', tr: 'Yeni kart oluşturuldu', ru: 'Создана новая карточка', ka: 'შეიქმნა ახალი ბარათი' },
  'Ən azı 1 bilet olmalıdır': { en: 'At least 1 ticket is required', tr: 'En az 1 bilet olmalı', ru: 'Нужен минимум 1 билет', ka: 'საჭიროა მინიმუმ 1 ბილეთი' },
  'İşarələr silindi':  { en: 'Marks cleared', tr: 'İşaretler silindi', ru: 'Отметки очищены', ka: 'აღნიშვნები გასუფთავდა' },
  'Avto rejim açıq':   { en: 'Auto mode on', tr: 'Otomatik mod açık', ru: 'Авторежим включён', ka: 'ავტორეჟიმი ჩართულია' },
  'Avto rejim bağlı':  { en: 'Auto mode off', tr: 'Otomatik mod kapalı', ru: 'Авторежим выключен', ka: 'ავტორეჟიმი გამორთულია' },
  'Səs aç/bağla':      { en: 'Sound on/off', tr: 'Sesi aç/kapat', ru: 'Звук вкл/выкл', ka: 'ხმა ჩართ./გამორთ.' },
  'Səs açıldı':        { en: 'Sound on', tr: 'Ses açıldı', ru: 'Звук включён', ka: 'ხმა ჩაირთო' },
  'Səs bağlandı':      { en: 'Sound off', tr: 'Ses kapandı', ru: 'Звук выключен', ka: 'ხმა გამოირთო' },
  'Oyun başladı':      { en: 'The game has started', tr: 'Oyun başladı', ru: 'Игра началась', ka: 'თამაში დაიწყო' },
  'Raund tamamlandı':  { en: 'Round complete', tr: 'Tur tamamlandı', ru: 'Раунд завершён', ka: 'რაუნდი დასრულდა' },
  'Uduş balansınıza əlavə olundu': { en: 'The prize was added to your balance', tr: 'Ödül bakiyene eklendi', ru: 'Выигрыш зачислен на баланс', ka: 'მოგება დაემატა ბალანსს' },
  'Qazandınız! +':     { en: 'You won! +', tr: 'Kazandın! +', ru: 'Вы выиграли! +', ka: 'მოიგეთ! +' },
  'Oyuna qayıt':       { en: 'Back to the game', tr: 'Oyuna dön', ru: 'Вернуться в игру', ka: 'თამაშში დაბრუნება' },
  'Oyundan çıx':       { en: 'Leave the game', tr: 'Oyundan çık', ru: 'Выйти из игры', ka: 'თამაშიდან გასვლა' },
  'Oyunda qal':        { en: 'Stay in the game', tr: 'Oyunda kal', ru: 'Остаться в игре', ka: 'თამაშში დარჩენა' },
  'Oyundan çıxmaq istəyirsiniz?': { en: 'Do you want to leave the game?', tr: 'Oyundan çıkmak istiyor musun?', ru: 'Выйти из игры?', ka: 'გსურთ თამაშის დატოვება?' },
  'Çıx (30% geri)':    { en: 'Leave (30% back)', tr: 'Çık (%30 geri)', ru: 'Выйти (30% назад)', ka: 'გასვლა (30% უკან)' },
  'Vaxt bitdi — bu daş bloklandı': { en: 'Time is up — this ball is blocked', tr: 'Süre doldu — bu taş bloke edildi', ru: 'Время вышло — шар заблокирован', ka: 'დრო ამოიწურა — ბურთი დაიბლოკა' },
  'Oyun necə oynanılır?': { en: 'How is the game played?', tr: 'Oyun nasıl oynanır?', ru: 'Как играть?', ka: 'როგორ ვითამაშოთ?' },
  'Oyun haqqında məlumat': { en: 'About the game', tr: 'Oyun hakkında bilgi', ru: 'Об игре', ka: 'თამაშის შესახებ' },
  'Qazanc necə hesablanır?': { en: 'How are winnings calculated?', tr: 'Kazanç nasıl hesaplanır?', ru: 'Как считается выигрыш?', ka: 'როგორ ითვლება მოგება?' },
  'Otaq qaydaları':    { en: 'Room rules', tr: 'Oda kuralları', ru: 'Правила комнаты', ka: 'ოთახის წესები' },
  'Bilet rəqəmlərini': { en: 'Pick your ticket numbers with', tr: 'Bilet numaralarını', ru: 'Номера билета выберите', ka: 'ბილეთის ნომრები აირჩიეთ' },
  'ilə seçin, artıq bileti': { en: 'or, and remove the extra ticket with', tr: 'ile seç, fazla bileti', ru: 'или, лишний билет', ka: 'ან, ზედმეტი ბილეთი' },
  'Maksimum':          { en: 'Maximum', tr: 'Maksimum', ru: 'Максимум', ka: 'მაქსიმუმ' },
  'BİLET AL':          { en: 'BUY TICKET', tr: 'BİLET AL', ru: 'КУПИТЬ БИЛЕТ', ka: 'ბილეთის ყიდვა' },
  'TAM BİLET':         { en: 'FULL TICKET', tr: 'TAM BİLET', ru: 'ПОЛНЫЙ БИЛЕТ', ka: 'სრული ბილეთი' },
  'Qazan':             { en: 'Win', tr: 'Kazan', ru: 'Выигрыш', ka: 'მოგება' },
  'Oyuna qoşulduqda sizə avtomatik kart veriləcək.': { en: 'You will get a card automatically when you join the game.', tr: 'Oyuna katıldığında sana otomatik kart verilir.', ru: 'При входе в игру карточка выдаётся автоматически.', ka: 'თამაშში შესვლისას ბარათი ავტომატურად გეძლევათ.' },
  'yenilə':            { en: 'refresh', tr: 'yenile', ru: 'обновить', ka: 'განახლება' },
  'dəyiş':             { en: 'change', tr: 'değiştir', ru: 'заменить', ka: 'შეცვლა' },
  'sil':               { en: 'delete', tr: 'sil', ru: 'удалить', ka: 'წაშლა' },
  'avto':              { en: 'auto', tr: 'oto', ru: 'авто', ka: 'ავტო' },
  'avto açıq':         { en: 'auto on', tr: 'oto açık', ru: 'авто вкл', ka: 'ავტო ჩართ.' },
  '5 oyunçu':          { en: '5 players', tr: '5 oyuncu', ru: '5 игроков', ka: '5 მოთამაშე' },
  '5 bilet':           { en: '5 tickets', tr: '5 bilet', ru: '5 билетов', ka: '5 ბილეთი' },
  '5 rəqəm':           { en: '5 numbers', tr: '5 rakam', ru: '5 чисел', ka: '5 ციფრი' },
  '15 rəqəm':          { en: '15 numbers', tr: '15 rakam', ru: '15 чисел', ka: '15 ციფრი' },
  '3 sıradan (linya)': { en: '3 rows (lines)', tr: '3 sıradan (çizgi)', ru: '3 ряда (линии)', ka: '3 რიგი (ხაზი)' },
  'Mərc — bilet qiyməti (₼)': { en: 'Stake — ticket price', tr: 'Bahis — bilet fiyatı', ru: 'Ставка — цена билета', ka: 'ფსონი — ბილეთის ფასი' },

  // ── Wallet / deposit əlavələri ──
  'Əvvəlcə ödəniş üsulunu seçin': { en: 'Choose a payment method first', tr: 'Önce ödeme yöntemini seç', ru: 'Сначала выберите способ оплаты', ka: 'ჯერ აირჩიეთ გადახდის მეთოდი' },
  'Əvvəlcə çıxarış üsulunu seçin': { en: 'Choose a withdrawal method first', tr: 'Önce çekim yöntemini seç', ru: 'Сначала выберите способ вывода', ka: 'ჯერ აირჩიეთ გატანის მეთოდი' },
  'Son istifadə tarixi (varsa)': { en: 'Expiry date', tr: 'Son kullanma tarihi', ru: 'Срок действия', ka: 'მოქმედების ვადა' },
  'Balans':            { en: 'Balance', tr: 'Bakiye', ru: 'Баланс', ka: 'ბალანსი' }
};
